export const DATA_LOADING = 'DATA_LOADING';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const LOADING_FAILURE = 'LOADING_FAILURE';
export const CHANGE_MOVIES_PAGE = 'CHANGE_MOVIES_PAGE';
export const CHANGE_MOVIES_SORT = 'CHANGE_MOVIES_SORT';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
