export const GET_DATA_STARTED = 'GET_MOVIES_STARTED';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const CHANGE_MOVIES_PAGE = 'CHANGE_MOVIES_PAGE';
